name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for better compatibility
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Java 17  # Use Java 17 as required by Android SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache Buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
        
    - name: Make buildozer executable
      run: |
        export PATH=$PATH:~/.local/bin
        
    - name: Build APK with Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug
        
    - name: Get APK path and info
      id: apk-info
      run: |
        APK_PATH=$(find bin -name "*.apk" | head -1)
        if [ -z "$APK_PATH" ]; then
          echo "No APK found in bin directory!"
          echo "Contents of current directory:"
          ls -la
          echo "Looking for APK files recursively:"
          find . -name "*.apk" -type f
          exit 1
        fi
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
        echo "Found APK at: $APK_PATH"
        
        # Extract version from tag or use manual trigger
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="manual-$(date +%Y%m%d-%H%M%S)"
        else
          VERSION=${GITHUB_REF#refs/tags/}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.apk-info.outputs.version }}
        name: Open E-Dope ${{ steps.apk-info.outputs.version }}
        body: |
          ## 🎯 Open E-Dope - NFC E-Paper Display App
          
          ### What's New in ${{ steps.apk-info.outputs.version }}
          - ✅ Fixed 2.9-inch B&W display refresh command
          - ✅ Corrected EPD initialization strings for all display types  
          - ✅ Improved NFC communication protocol
          - ✅ Added proper screen cut commands for SSD1680 displays
          
          ### Supported E-Paper Displays
          - **Good Display 2.9-inch B&W** (SSD1680, 296×128)
          - **Good Display 3.7-inch** (UC8171, 240×416)
          - **Good Display 4.2-inch B&W** (SSD1680, 400×300)
          
          ### Installation
          1. Download the APK file below
          2. Enable "Install from Unknown Sources" on your Android device
          3. Install the APK
          4. Grant NFC permissions when prompted
          
          ### Usage
          - Create or import CSV data cards
          - Hold your NFC e-paper display near your phone
          - The app will automatically transfer and refresh the display
        draft: false
        prerelease: false
        files: ${{ steps.apk-info.outputs.apk_path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}