name: Build and Release APK (Simple)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-20.04  # Use older Ubuntu for better compatibility
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade pip
        pip install buildozer cython==0.29.33
        
    - name: Build APK
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        buildozer android debug || echo "Build completed with warnings"
        
    - name: Find APK
      id: find-apk
      run: |
        # Look for APK in multiple locations
        APK_PATH=""
        for dir in bin .buildozer/android/platform/build*/dists/*/bin; do
          if [ -d "$dir" ]; then
            APK_FILE=$(find "$dir" -name "*.apk" | head -1)
            if [ ! -z "$APK_FILE" ]; then
              APK_PATH="$APK_FILE"
              break
            fi
          fi
        done
        
        if [ ! -z "$APK_PATH" ]; then
          echo "apk_found=true" >> $GITHUB_OUTPUT
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK at: $APK_PATH"
        else
          echo "apk_found=false" >> $GITHUB_OUTPUT
          echo "No APK found"
        fi
        
    - name: Upload APK as Artifact
      if: steps.find-apk.outputs.apk_found == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: Open-E-Dope-APK-${{ github.run_number }}
        path: ${{ steps.find-apk.outputs.apk_path }}
        
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/') && steps.find-apk.outputs.apk_found == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find-apk.outputs.apk_path }}
        body: |
          ## 🎯 Open E-Dope - NFC E-Paper Display App
          
          ### What's New
          - ✅ Fixed 2.9-inch B&W display refresh command
          - ✅ Corrected EPD initialization strings for all display types
          - ✅ Improved NFC communication protocol
          
          ### Supported E-Paper Displays
          - **Good Display 2.9-inch B&W** (SSD1680, 296×128)
          - **Good Display 3.7-inch** (UC8171, 240×416)
          - **Good Display 4.2-inch B&W** (SSD1680, 400×300)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}