name: Build and Release APK

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1, etc.

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Buildozer & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libmtdev-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libgstreamer-plugins-base1.0-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libpng-dev
          pip install --upgrade pip
          pip install --user Cython==0.29.33
          pip install --user --upgrade buildozer

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android release

      - name: Find APK
        id: apk
        run: |
          APK_PATH=$(ls bin/*.apk | head -n 1)
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}