name: Build Kivy APK with Buildozer

on:
  push:
    tags:
      - 'v*'  # e.g., v1.0.0

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git zip unzip openjdk-17-jdk
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}