name: Build & Release APK with Buildozer

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Buildozer & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libmtdev-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libgstreamer-plugins-base1.0-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libpng-dev

          pip install --upgrade Cython
          pip install --user buildozer

      - name: Add buildozer to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}